# Generated by Django 2.2.5 on 2019-09-12 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inicio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relator',
            name='edad',
            field=models.IntegerField(null=True),
        ),
    ]
